package seedr

var loremipsum = []rune(
	`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec lacus finibus, tempor est ac, suscipit mauris. Donec in rutrum neque, a pharetra tortor. Duis enim dolor, elementum sit amet mi eu, tristique malesuada dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum volutpat nisi, sed pulvinar quam dignissim semper. Fusce congue, ligula in pharetra ultricies, lorem nunc egestas urna, vel sodales libero odio sed velit. Integer ullamcorper consectetur arcu ut sodales. Cras at libero et nulla pellentesque consequat. Sed venenatis nisl quis vulputate porta. Nam pretium odio et odio gravida fringilla. Cras sit amet velit vitae tellus auctor sodales vitae eu quam. Ut cursus mauris quis luctus lobortis.

Proin purus purus, vestibulum eu ultricies nec, scelerisque ac diam. Suspendisse consequat urna vel massa eleifend ultricies. Mauris tempor rutrum sollicitudin. Vivamus ut malesuada enim. Phasellus faucibus lacus congue nisi iaculis, eu facilisis magna dapibus. Integer nec diam sem. Ut leo ligula, rutrum eget lectus non, faucibus lacinia libero. Phasellus arcu diam, consectetur in mollis quis, laoreet sed tortor. Praesent congue, eros at bibendum accumsan, ligula tortor tincidunt enim, quis laoreet quam sapien ac turpis. Etiam sagittis et dolor sed elementum. Curabitur eu libero in dui aliquam varius. Nulla consequat sed nibh id tristique. Sed tristique nisl imperdiet dui rutrum malesuada. Vestibulum id elementum justo. Phasellus in enim mollis purus viverra egestas non vitae nibh.

Integer in cursus elit. Morbi at sodales nulla. Phasellus quis imperdiet nunc. Pellentesque justo leo, efficitur cursus ipsum id, euismod gravida tellus. Ut tristique consectetur ligula a accumsan. Ut eget dapibus velit. Fusce pharetra euismod erat, eu sodales nunc imperdiet sit amet. Nullam dictum maximus semper. Aenean a porttitor lorem, eget pharetra diam. Etiam mattis, orci sit amet fringilla posuere, sapien est eleifend urna, a aliquam augue lectus egestas velit. Integer id consectetur nibh. Maecenas pretium at augue nec aliquet. Aliquam erat volutpat. Vivamus quis elit molestie, ullamcorper enim at, consectetur nulla. Nullam rutrum orci nec orci gravida, a aliquet mi condimentum. Etiam gravida posuere mauris non sagittis.

Curabitur nec lectus fringilla, fermentum nibh sit amet, condimentum tellus. Duis tortor sem, pellentesque ut mollis vel, semper at massa. Nulla consequat est ac venenatis tempus. Nunc luctus diam eu orci consectetur, eleifend consequat enim sagittis. Curabitur sed volutpat sem. Integer non pretium augue. Mauris hendrerit neque vitae interdum convallis. Sed eget leo nec dolor tristique interdum vel vitae lorem. Duis ultrices mauris eu rutrum euismod. Suspendisse rhoncus euismod blandit.

Donec non velit eget arcu rhoncus bibendum vitae eu nibh. Aenean nec urna in est blandit varius. Pellentesque id lacus nec orci dapibus varius aliquam sit amet nulla. Aenean in facilisis leo. Suspendisse ut ipsum tristique, interdum libero in, cursus eros. Vivamus mi justo, egestas quis iaculis nec, dignissim a quam. Nullam luctus velit in quam auctor, id ornare sem blandit. Nullam sed odio id tortor sodales interdum. Nam ut sapien ut massa eleifend cursus. Quisque in neque quis diam pretium suscipit. Curabitur pulvinar laoreet turpis id congue.`)
